name: convert-to-rkllm
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11

  - conda-forge::pytorch==2.7.0

  - pip:
    # python < 3.12 https://github.com/AutoGPTQ/AutoGPTQ/issues/730
    # - git+https://github.com/PanQiWei/AutoGPTQ.git@v0.7.1
    - rknn-llm/rkllm-toolkit/rkllm_toolkit-1.2.1-cp311-cp311-linux_x86_64.whl

    - gradio
