
FROM pytorch/pytorch:2.7.0-cuda12.6-cudnn9-runtime

WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     libstdc++6 \
#     && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    gradio==5.34.2 \
    https://github.com/airockchip/rknn-llm/raw/refs/tags/release-v1.2.1/rkllm-toolkit/rkllm_toolkit-1.2.1-cp311-cp311-linux_x86_64.whl

COPY ./gradio /workspace/gradio
WORKDIR /workspace/gradio


EXPOSE 7860

VOLUME /root/.cache
VOLUME /root/.rkllm-build

ENV HUGGINGFACE_HUB_CACHE=/root/.cache/huggingface/hub
ENV OUTPUT_DIR=/root/.rkllm-build/models/
ENV LOG_DIR=/root/.rkllm-build/logs/
ENV DATASET_JSON=/workspace/gradio/dataset.json

CMD ["gradio", "app.py"]
