
name: Docker Image Build/Publish tag with commit

on:
  push:
    branches:
      - 'main'
    paths:
      - gradio/**
      - docker/build@source/dockerfile
      - .github/workflows/docker-image-tag-commit.yml

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        platforms:
          - linux/amd64

    steps:
      # Fix github action 'No space left on device'
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get git short head
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7

      - name: Meta data image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/convert-to-rkllm
            ghcr.io/${{ github.repository_owner }}/convert-to-rkllm
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=${{ steps.short-sha.outputs.sha }}
          flavor: |
            latest=false

      - name: Build push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/build@source/dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print image digest
        run: echo ${{ steps.build.outputs.digest }}
